config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root to: 'index#show'

	get '/video/:id' => 'index#video', as: 'video'
    get '/show/:id' => 'index#show', as: 'report'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def show
    @video_id = params[:id]
  end

  def video

    @video_id = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/show.html.erb
<html>
<head>
  <meta charset="utf-8">
  <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.2/fetch.min.js'></script>

  <style>
    .chart {
        width: 640px;
    }
  </style>
</head>
<body>
  <div class="chart">
      <canvas id="myChart"></canvas>
  </div>
  
  <br />
  <center class="chart">
    <%= link_to "Home", video_path(id: @video_id) %>
  </center>

  <script>

  fetch('https://api.keen.io/3.0/projects/589b3df48db53dfda8a86e59/queries/count?api_key=3EDC23F7F23923C3E67F91A5CD4CBE642BC69997A06DD1078064B1A6CE9F221CD3C988937F6B3A0A69FE84385F109FE1E3090B9BDBDED0049649415F9E8AA1F6DA052F0CE0539FBA059B4447C1734B22DA73EB22B2D98499A6A3C219FA054079&event_collection=video-interaction&interval=hourly&timezone=UTC&timeframe=this_1_days&filters=%5B%5D')
    .then((res) => {
      // JSON.parse(res.body.readableStream)
      return res.json();
    })
    .then(res => {
      const chartData = {
        type: 'line',
        data: {
          labels: [],
          datasets: [{
            label: 'Number of interactions',
            data: [],
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
              'rgba(255,99,132,1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)',
              'rgba(75, 192, 192, 1)',
              'rgba(153, 102, 255, 1)',
              'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero:true
              }
            }]
          }
        }
      }
      const data = res.result;
      console.log(data)
      data.map(d => {
        // console.log(chartData.data.datasets[0])
        chartData.data.labels.push(d.timeframe.start.substring(11, 13)+'h')
        chartData.data.datasets[0].data.push(d.value)
        // console.log(d.value)
      })
      console.log(chartData)
      const ctx = document.getElementById("myChart");
      const myChart = new Chart(ctx, chartData);
    })

  </script>
</body>
</html>

app/views/index/video.html.erb
<html>
<head>
  <meta charset="utf-8">
  <script src="http://d26b395fwzu5fz.cloudfront.net/keen-tracking-1.0.5.js"></script>
</head>
<body>

  <style>
    .chart {
        width: 640px;
    }
  </style>

  <iframe id="youtube-iframe-player"
          width="640" height="360"
          src="https://www.youtube.com/embed/<%= @video_id %>?enablejsapi=1"
          frameborder="0"
          style="border: solid 4px #37474F"></iframe>

  <br />
  <center class="chart">
    <%= link_to "Report", report_path(id: @video_id) %>
  </center>

  <script>
  /*
    Learn more about the Youtube iFrame Player API here:
    https://developers.google.com/youtube/iframe_api_reference

    Learn more about keen-tracking.js here:
    https://github.com/keen/keen-tracking.js
  */

  // Install YouTube SDK
  var newTag = document.createElement('script');
  newTag.src = 'https://www.youtube.com/iframe_api';
  var firstTag = document.getElementsByTagName('script')[0];
  firstTag.parentNode.insertBefore(newTag, firstTag);

  function onYouTubeIframeAPIReady() {
    var player = new YT.Player('youtube-iframe-player');
    trackEvents(player);
  }

  function trackEvents(player) {
    var client = new Keen({
      projectId: '589b3df48db53dfda8a86e59',
      writeKey: 'A908485C5E1DD6ACE282A9F398EAF52DCFFDEBC980E5B75C18E26B9553B532D23741A04D9F2661CB53327A2D32A6429BF150FE6223AB812116595144E23D73410303004A40ACCC1098734F40EA27B435810DD0F36C356298A4FE53C5B4CA03A1'
    });

    // These flags can help with local development
    Keen.debug = true;
    // Keen.enabled = false;
    client.on('recordEvent', console.log);

    client.extendEvents(function(){
      return {
        browser: Keen.helpers.getBrowserProfile(),
        player: {
          'is-muted': player.isMuted(),
          'current-position': player.getCurrentTime(),
          'duration': player.getDuration(),
          'playback-quality': player.getPlaybackQuality(),
          'volume': player.getVolume()
        }
      }
    });

    player.addEventListener('onStateChange', function(e) {

      console.log(e);

      var state = e.data;
      if (state === 1) {
        client.recordEvent('video-interaction', { event_type: 'started' });
      }
      else if (state === 2) {
        client.recordEvent('video-interaction', { event_type: 'paused' });
      }
      else if (state === 0) {
        client.recordEvent('video-interaction', { event_type: 'finished' });
      }
    }, false);

    player.addEventListener('onError', function(e) {
      client.recordEvent('video-interaction', { event_type: 'error' });
    }, false);
  }
  </script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videotracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>